path_dap: 'C:/Users/SLETIZIA/OneDrive - NREL/Desktop/PostDoc/Custom_functions/dap-py'
path_utils: 'C:/Users/SLETIZIA/OneDrive - NREL/Desktop/PostDoc/utils'
username: 'sletizia'
password: 'pass_DAP1506@'
                